# Generated by Django 5.1.6 on 2025-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_uploadedfile_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
