# Generated by Django 5.1.6 on 2025-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
