# Generated by Django 5.1.6 on 2025-04-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="book_description",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="book_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
