# Generated by Django 5.1.6 on 2025-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_mobile",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
