# Generated by Django 5.1.6 on 2025-04-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_uploadedfile_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
