# Generated by Django 5.1.6 on 2025-04-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_uploadedfile_book_description_uploadedfile_book_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("publisher", "Publisher"),
                    ("author", "Author"),
                ],
                max_length=20,
            ),
        ),
    ]
