# Generated by Django 5.1.6 on 2025-04-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_uploadedfile_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("publisher", "Publisher"),
                    ("author", "Author"),
                    ("customer", "Customer"),
                ],
                max_length=20,
            ),
        ),
    ]
