# Generated by Django 5.1.6 on 2025-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="uploaded_files",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="user.uploadedfile"
            ),
        ),
    ]
