# Generated by Django 5.1.6 on 2025-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processedpdf",
            name="uploaded_file",
        ),
        migrations.RemoveField(
            model_name="processedpdf",
            name="user",
        ),
        migrations.DeleteModel(
            name="ProcessedImage",
        ),
        migrations.DeleteModel(
            name="ProcessedPDF",
        ),
    ]
